### ISSUE TITLE
Download a podcast gives "a file with the same name already exists"

### ISSUE THREAD

**Issue by jroman** [choorp/foxcasts#3]
Hi,

anything to say about functionality in different versions of FOS?

I find it difficult to download a podcast. I get a message about "a file with the same name already exists" after 100% download.

FOS 1.3, alcatel one toch fire C and no micro SD card (just internal storage)

**Comment by Caliandroid** [comment]
Hi,
i've encountered the same problem and checked the adb log.
In the following example on my ZTE Open C with FFOS 2.2 and sd card
i've tried to download the podcast "Ludwig Beck - vom Generalstabschef zu Hitlers Widersacher".
Source SWR Wissen (Feed: http://www1.swr.de/podcast/xml/swr2/wissen.xml )

Logcat output:

```
I/FoxCasts( 2090):     at PodcastManager.subscribe/a.oncomplete< (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:4057)
I/FoxCasts( 2090): Content JS LOG: DownloadManager.download(): Ludwig Beck - vom Generalstabschef zu Hitlers Widersacher 
I/FoxCasts( 2090):     at DownloadManager.download (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:62)
I/FoxCasts( 2090): Content JS LOG: [object Object] 
I/FoxCasts( 2090):     at DownloadManager.download (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:122)
I/FoxCasts( 2090): Content JS LOG: [object Event] 
I/FoxCasts( 2090):     at DownloadManager.download/n.onreadystatechange (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:395)
I/FoxCasts( 2090): Content JS LOG: Download finished! 
I/FoxCasts( 2090):     at DownloadManager.download/n.onreadystatechange (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:410)
I/FoxCasts( 2090): Content JS LOG: ready to store file... 
I/FoxCasts( 2090):     at StorageManager.store (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:764)
I/FoxCasts( 2090): Content JS LOG: [object DeviceStorage] 
I/FoxCasts( 2090):     at StorageManager.store (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:844)
W/FoxCasts( 2090): Content JS WARN: Unable to write the file 
W/FoxCasts( 2090):     at StorageManager.store/s.onerror (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:1102)
```

I get the error message for all podcast from this source. 
I've reinstalled the app without success.

**Comment by garredow** [comment]
Thanks for the detailed report, guys. I'll have a chance to look into it this weekend at the latest.
