### ISSUE TITLE
Database corrupt after reboot

### ISSUE THREAD

**Issue by Caliandroid** [choorp/foxcasts#5]
i don't know if the problem comes from particular podcast feeds but if i add all favoured podcasts (7 feeds), everything works like expected
but after a reboot the db seems to be broken.

Only solution: Delete and reinstall but it will happen again if i add my feeds.

```
W/FoxCasts( 1557): [JavaScript Warning: "Unknown property 'user-select'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 62 column: 12 source: "  user-select: none;"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 65 column: 20 source: ".enyo-unselectable::selection, .enyo-unselectable ::selection {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown property 'user-select'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 74 column: 12 source: "  user-select: text;"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 77 column: 18 source: ".enyo-selectable::selection, .enyo-selectable ::selection {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element '-webkit-full-screen'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 113 column: 1 source: ":-webkit-full-screen {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element '-ms-full-screen'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 121 column: 1 source: ":-ms-full-screen {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element '-o-full-screen'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 125 column: 1 source: ":-o-full-screen {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element 'full-screen'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 129 column: 1 source: ":full-screen {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 269 column: 9 source: "   filter: alpha(opacity=65);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 310 column: 10 source: "  filter: alpha(opacity=0);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.css" line: 322 column: 10 source: "  filter: alpha(opacity=100);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'display'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 155 column: 10 source: "    display: -webkit-box;"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'display'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 157 column: 10 source: "    display: -ms-flexbox;"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'display'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 158 column: 10 source: "    display: -webkit-flex;"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 366 column: 9 source: "    filter: alpha(opacity=40);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 550 column: 10 source: "  filter: alpha(opacity=40);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 604 column: 10 source: "  filter: alpha(opacity=40);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 725 column: 10 source: "  filter: alpha(opacity=40);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown property 'user-select'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 789 column: 13 source: "  user-select: none;"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 791 column: 10 source: "  filter: alpha(opacity=40);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1010 column: 14 source: "  background: -webkit-linear-gradient(left, rgba(177, 177, 177, 0), #b1b1b1);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1012 column: 14 source: "  background: -webkit-gradient(linear, right top, left top, color-stop(0%, #b1b1b1), color-stop(100%, rgba(177, 177, 177, 0)));"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1014 column: 14 source: "  background: -o-linear-gradient(left, #b1b1b1 0%, rgba(177, 177, 177, 0) 100%);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1016 column: 14 source: "  background: -ms-linear-gradient(left, rgba(177, 177, 177, 0) 0%, #b1b1b1 100%);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1018 column: 10 source: "  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#00b1b1b1, endColorstr=#ffb1b1b1, GradientType=1);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1026 column: 14 source: "  background: -webkit-linear-gradient(left, rgba(202, 202, 202, 0), #cacaca);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1028 column: 14 source: "  background: -webkit-gradient(linear, right top, left top, color-stop(0%, #cacaca), color-stop(100%, rgba(202, 202, 202, 0)));"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1030 column: 14 source: "  background: -o-linear-gradient(left, #cacaca 0%, rgba(202, 202, 202, 0) 100%);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1032 column: 14 source: "  background: -ms-linear-gradient(left, rgba(202, 202, 202, 0) 0%, #cacaca 100%);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1034 column: 10 source: "  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#00cacaca, endColorstr=#ffcacaca, GradientType=1);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1042 column: 14 source: "  background: -webkit-linear-gradient(left, rgba(202, 202, 202, 0), #cacaca);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1044 column: 14 source: "  background: -webkit-gradient(linear, right top, left top, color-stop(0%, #cacaca), color-stop(100%, rgba(202, 202, 202, 0)));"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1046 column: 14 source: "  background: -o-linear-gradient(left, #cacaca 0%, rgba(202, 202, 202, 0) 100%);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1048 column: 14 source: "  background: -ms-linear-gradient(left, rgba(202, 202, 202, 0) 0%, #cacaca 100%);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1050 column: 10 source: "  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#00cacaca, endColorstr=#ffcacaca, GradientType=1);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1107 column: 10 source: "  filter: alpha(opacity=40);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1181 column: 55 source: ".onyx-toolbar .onyx-input-decorator .onyx-input:focus::-webkit-input-placeholder {"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background-image'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1261 column: 20 source: "  background-image: -webkit-gradient(linear, 0 100%, 100% 0, color-stop(0.25, rgba(255, 255, 255, 0.15)), color-stop(0.25, transparent), color-stop(0.5, transparent), color-stop(0.5, rgba(255, 255, 255, 0.15)), color-stop(0.75, rgba(255, 255, 255, 0.15)), color-stop(0.75, transparent), to(transparent));"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background-image'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1262 column: 20 source: "  background-image: -webkit-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background-image'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1264 column: 20 source: "  background-image: -ms-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Error in parsing value for 'background-image'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1265 column: 20 source: "  background-image: -o-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);"}]
W/FoxCasts( 1557): [JavaScript Warning: "Unknown property 'text-size'.  Declaration dropped." {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.css" line: 1956 column: 11 source: "  text-size: 10px;"}]
I/FoxCasts( 1557): Content JS LOG: Settings.loadAppPrefs(): [object Object] 
I/FoxCasts( 1557):     at e.logging._log (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/enyo.js:21:497)
I/FoxCasts( 1557): Content JS LOG: [object Object] 
I/FoxCasts( 1557):     at .create (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:204:1454)
I/FoxCasts( 1557): Content JS LOG: PodcastManager.initialize(): Database_Production, 1 
I/FoxCasts( 1557):     at PodcastManager.initialize (app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js:201:2218)
W/FoxCasts( 1557): [JavaScript Error: "QuotaExceededError" {file: "app://{8dffa715-4591-4a05-92af-7bcbbec5cae7}/build/app.js" line: 201}]
```

**Comment by garredow** [comment]
Interesting. At first glance, it looks like the indexeddb has reached its storage limit. I'll need to look into this more.

**Comment by Caliandroid** [comment]
If i can provide you with more information, let me know.
I have a 32gb sd card with currently 25gb free space.
